### ISSUE TITLE
Mobile toasts are not full width

### ISSUE THREAD

**Issue by Sceat** [shakee93/vue-toasted#123]
It says
![image](https://user-images.githubusercontent.com/11330271/56501080-27a01800-6516-11e9-9a99-e2ef4144f04c.png)

but ?

![image](https://user-images.githubusercontent.com/11330271/56501060-122aee00-6516-11e9-812f-73ebca515c6c.png)

**Comment by Sceat** [comment]
Fixed in #127 👉 awaiting @shakee93 to go out of hibernation 😀

**Comment by luffyzc** [comment]
looks like the toast in demo page is still not fullWidth  

![Screen Shot 2020-11-08 at 4 32 38 PM](https://user-images.githubusercontent.com/7036765/98488859-49d4b600-21e0-11eb-94cc-90840adbeb51.png)
